export const USER_STATE_CHANGE_REQUEST = 'USER_STATE_CHANGE_REQUEST';
export const USER_STATE_CHANGE_SUCCESS = 'USER_STATE_CHANGE_SUCCESS';
export const USER_STATE_CHANGE_FAIL = 'USER_STATE_CHANGE_FAIL';
export const USER_STATE_CHANGE_RESET = 'USER_STATE_CHANGE_RESET';

export const USER_POST_STATE_CHANGE_REQUEST = 'USER_POST_STATE_CHANGE_REQUEST';
export const USER_POST_STATE_CHANGE_SUCCESS = 'USER_POST_STATE_CHANGE_SUCCESS';
export const USER_POST_STATE_CHANGE_FAIL = 'USER_POST_STATE_CHANGE_FAIL';

export const USER_FOLLOWING_STATE_CHANGE_REQUEST =
  'USER_FOLLOWING_STATE_CHANGE_REQUEST';
export const USER_FOLLOWING_STATE_CHANGE_SUCCESS =
  'USER_FOLLOWING_STATE_CHANGE_SUCCESS';
export const USER_FOLLOWING_STATE_CHANGE_FAIL =
  'USER_FOLLOWING_STATE_CHANGE_FAIL';

  export const USERS_DATA_STATE_CHANGE_REQUEST =
    'USERS_DATA_STATE_CHANGE_REQUEST';
  export const USERS_DATA_STATE_CHANGE_SUCCESS =
    'USERS_DATA_STATE_CHANGE_SUCCESS';
export const USERS_DATA_STATE_CHANGE_FAIL = 'USERS_DATA_STATE_CHANGE_FAIL';
  
export const USERS_POSTS_STATE_CHANGE_REQUEST = 'USERS_POSTS_STATE_CHANGE_REQUEST';
export const USERS_POSTS_STATE_CHANGE_SUCCESS = 'USERS_POSTS_STATE_CHANGE_SUCCESS';
export const USERS_POSTS_STATE_CHANGE_FAIL = 'USERS_POSTS_STATE_CHANGE_FAIL';

export const USERS_LIKES_STATE_CHANGE_REQUEST = 'USERS_LIKES_STATE_CHANGE_REQUEST';
export const USERS_LIKES_STATE_CHANGE_SUCCESS = 'USERS_LIKES_STATE_CHANGE_SUCCESS';
export const USERS_LIKES_STATE_CHANGE_FAIL = 'USERS_LIKES_STATE_CHANGE_FAIL';